# STAGE 1: Chef (Prepare the recipe)

FROM rustlang/rust:nightly-alpine as chef
# Install system dependencies required for cargo-chef and build
RUN apk add --no-cache musl-dev
RUN cargo install cargo-chef
WORKDIR /app

# STAGE 2: Planner (Compute the lockfile)

FROM chef as planner
COPY . .
# Creates a recipe.json file that describes your dependencies
RUN cargo chef prepare --recipe-path recipe.json

# =================================================================
# STAGE 3: Builder (Compile deps + Build App)
# =================================================================
FROM chef as builder

# 1. Install External Tools (Cached layer)
# Added nodejs (required for npm), npm, binaryen (wasm-opt), curl
RUN apk add --no-cache bash curl npm libc-dev binaryen nodejs

# 2. Install SASS (Cached layer)
RUN npm install -g sass

# 3. Install Cargo-Leptos (Cached layer)
# We assume v0.2.40 as per your request.
RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/leptos-rs/cargo-leptos/releases/download/v0.2.40/cargo-leptos-installer.sh | sh

# 4. Add WASM Target (Cached layer)
RUN rustup target add wasm32-unknown-unknown

# 5. COOK DEPENDENCIES (The Magic Step)
# We copy ONLY the recipe.json. Docker sees this hasn't changed, so it uses the cache!
COPY --from=planner /app/recipe.json recipe.json

# Build dependencies - this will be cached until Cargo.toml changes
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json

# 6. BUILD THE APP
# Now we copy the source code. Since deps are built above, this step is fast.
COPY . .

# Run the actual build
RUN cargo leptos build --release -vv

# =================================================================
# STAGE 4: Runner (Final minimal image)
# =================================================================
# We use a bare Alpine image, not the heavy Rust one.
FROM alpine:latest as runner

WORKDIR /app

# Install runtime dependencies (if needed for SSL/HTTPS calls)
RUN apk add --no-cache ca-certificates

# Copy the binary from builder
COPY --from=builder /app/target/release/token-app /app/

# Copy the site assets (JS, WASM, CSS) generated by cargo-leptos
COPY --from=builder /app/target/site /app/site

# Copy config files if needed (Optional, removed Cargo.toml as it's usually not needed at runtime)
# COPY --from=builder /app/Cargo.toml /app/ 

ENV RUST_LOG="info"
ENV LEPTOS_SITE_ADDR="0.0.0.0:8080"
ENV LEPTOS_SITE_ROOT=./site

EXPOSE 8080

CMD ["/app/token-app"]
